### PR TITLE
Settings Refresh

### PR DESCRIPTION
**Pull request by mrhcjones**
**Why?**
In the future we may need more categories (for example Tweet Card Customisation) and currently the UI doesn't allow that to happen. Please let me know of any changes you would make to it as this is a major change.

**Settings UI**
* BottomNavigationBar -> Categories List
* Future Proof

**General Settings**
* Sub-category: `Media`
* Sub-category: `Feed`

**Theme Settings**
* Moved: `Font Size`

### CODE REVIEW

**Comment by j-fbriere** [comment]
Thank you for this PR.
I agree with the general idea of restructuring the settings to allow extending it.
I don't agree with the simplified list of color selection. or instance I'm using right now a color that is not even in the list.
I will accept this PR if you roll back the color list selection.

**Comment by mrhcjones** [comment]
Thank you for the feedback, I'll revert the colour options as soon as I'm
able to.

**Comment by mrhcjones** [comment]
@j-fbriere I have reverted the colour selection, any more feedback before you merge?

**Comment by j-fbriere** [comment]
You removed Experiments?

**Comment by mrhcjones** [comment]
Yes, it is intentional as I feel there is no need for it

**Comment by mrhcjones** [comment]
Thank you, for the quick response. I hope to be working more on Squawker in
the future 😃

**Pull request merged**
