### PR TITLE
More Post Card Customisation

### PR DESCRIPTION
**Pull request by mrhcjones**
For better customisation I have decided to start work on post card settings. Currently the settings are...
* Moved: `Font Size`
* `Profile image` - Disable/Enable profile images
- Added: `Profile image style`
* Moved `Media size`
- Added: `Hide card actions`
- Added: `Hide card numbers`
I have also fixed these issues in relation to the post cards:
#129

I am taking inspiration from the [Twidere](https://twidere.com) customisation settings for this

### CODE REVIEW

**Comment by j-fbriere** [comment]
Great! Thank you. I'll have a look, test it on my device and get back very soon.

**Comment by j-fbriere** [comment]
I tested it.
Great work.
Is the setting to enable/disable the profile image working? It had no effect for me.
Question: why is this new settings section called **Post Theme**?

**Comment by mrhcjones** [comment]
Thanks for the feedback I would also like to add:
* Enable/disable profile image is currently not working correctly
* Thanks for letting me know that `Square Avatars?` doesn't apply everywhere, I'll make sure to fix that
* `Post Theme` is a placeholder until we have a better name idea
↳ Feel free to suggest a better name

**Comment by j-fbriere** [comment]
Tested it and there is an error when trying to display the tweets.
It is because **optionActions** is never initialized. 
It throws an error (type 'Null' is not a subtype of type 'bool') at the following line (# 694) of **lib/tweet/tweet.dart**: 
`if (!prefs.get(optionActions))`

As you know, you have to initialize this option in **lib/main.dart** file under the block:
```
final prefService = await PrefServiceShared.init(prefix: 'pref_', defaults: {
  ...
```

**Comment by mrhcjones** [comment]
Thank you for bringing this up, I'll make sure to fix it when I am not busy

**Pull request closed without merging**
