### PR TITLE
Allow custom LibreTranslate instance

### PR DESCRIPTION
**Pull request by zihu12**
Currently the translation API endpoints are predefined/hardcoded as follows: https://github.com/j-fbriere/squawker/blob/b0f95723086f21fda805c8b8fbe0f443f9547125/lib/utils/translation.dart#L37
This will work most of the time, but sometimes not, especially for users in special network condition
    (also while testing for this PR `libretranslate.de` had undergone 502/`Connection Refused` sometimes :(

What this PR does:
1. add an option in settings that allows to set customized LibTranslate Instance(with one default instance `translate.fedilab.app`)
2. Provide an option to enter API KEY to use when a custom instance is defined(Mainly for who use [Official Instance](https://libretranslate.com/) or running private instances)

~~Don't know why so many whitespace-related changed in `lib/settings/_general.dart` through not shown in VS Code. :(~~
~~`editor.formatOnSave` in `.vscode/settings.json` filled my diff with whitespace changes :(~~

### CODE REVIEW

**Review by TheHCJ — APPROVED** [review]
The code looks fine, can be merged

**Comment by j-fbriere** [comment]
Merged, thank you!

This is a great idea.

I decided to let a list of LibreTranslate instances do the translation, like before, and not only an instance.
The list can be reordered, instances can be added and removed.
Each instance can have it's own API key.

**Comment by j-fbriere** [comment]
I just did the following test:

- I opened the Squawker application
- I opened the Translators list window
- I added the new host translate.lotigara.ru and saved
- I deleted the 3 default hosts by swap/delete
- I saved the list with only the new host in it
- I closed the Squawker application
- I reopened the Squawker application
- I opened the Translators list: it was still only with the new host
- I translated a tweet with success

So everything works fine for me.

I'm not sure I understand what is your issue.

Could you please describe your issue in detail.
Could you please provide the precise steps to reproduce your issue. 

It will help me debug it.
Thank you.

**Comment by j-fbriere** [comment]
Like I said, there is no issue for me.

I described earlier in detail the test I did with success.

If I cannot reproduce an issue, I cannot find the bug to fix it.

You're talking about using an inspector to analyze "something", but it's not clear what it is that I have to analyze and more importantly, what is the issue to begin with.

Maybe you should create a new issue in which you describe what is the problem.
In your description please specify the steps in Squawker to reproduce the issue.
No need to write about the tools used to try to resolve the issue for now, especially since I don't understand what the problem is.

Thank you.

**Pull request merged**
